<?php

/**
 * @file
 * Views Field Formatter module.
 */

declare(strict_types = 1);

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function views_field_formatter_help($route_name, RouteMatchInterface $route_match) {
  $output = '';

  if ($route_name !== 'help.page.views_field_formatter') {
    return $output;
  }

  $output .= '<h3>' . \t('About') . '</h3>';
  $output .= '<p>' . \t("Provide a new field formatter: '<strong>View</strong>' for each field types and allows you to select a View and to use its result instead of the original field value.") . '</p>';
  $output .= '<h3>' . \t('More Information') . '</h3>';
  $output .= '<p>' . \t('for more information about this module please visit the <a href="@link">project page</a>', ['@link' => 'https://www.drupal.org/project/views_field_formatter']) . '</p>';

  return $output;
}
